### ISSUE TITLE
Question: How to use CSS Custom Properties effectively with styled-system?

### ISSUE THREAD

**Issue by andrewgadziksonos** [styled-system/styled-system#1437]
Hello! 

First off I just wanted to say thank you for this open source project.  It's amazing 🙌 

Is there a lifecycle hook in styled-system that I can use to intercept a styled prop for example,

```jsx
<SomeComponent color="primary" bg="secondary" />
``` 

and convert the output CSS to use custom properties?  I want the final CSS to look like the following,

```css
.some-random-css-class {
  background-color: var(--colors-primary);
  color: var(--colors-secondary);
}
```

Thank for very much in advance for your help,

Andrew
