### ISSUE TITLE
Wrong media query order

### ISSUE THREAD

**Issue by sarneeh** [styled-system/styled-system#561]
Hey! First of all, thank you again for this amazing library! :smile: 

I have a weird problem. Take a look at this example:

```js
<Button m={[1, null, 3]} p={[1, 2, 3]}>
  Test1
</Button>
```

This results in:

```css
@media screen and (min-width: 40em) {
    .gtxxcJ {
        padding: 8px;
    }
}

@media screen and (min-width: 52em) {
    .gtxxcJ {
        margin: 16px;
        padding: 16px;
    }
}

.gtxxcJ {
    margin: 4px;
    padding: 4px;
}
```

Which is wrong, as the lower media query is overriding the higher one (due to order in css).

Reproduction: https://codesandbox.io/embed/styled-system-media-query-problem-qbhnd

Version: `styled-system@4.2.3`. This also happens in `5.x`, but behaves a little bit differently (you can check it by changing the version in `codesandbox`).

**Comment by jxnblk** [comment]
Thanks! This *appears* to be working in Chrome (at least on my end) and inspecting the injected CSS looks like styled-components is sorting the values differently than you have above. Where did you pull that CSS block from, and could you list out relevant versions of styled-components, Emotion, etc.?

**Comment by psullivan6** [comment]
I can also confirm this issue, which more precisely seems to happen when a prop using a larger breakpoint is listed before another prop using a smaller breakpoint. For instance, my similar usage:

### Similar usage
```jsx
<Box
  paddingTop={{ zero: 3, medium: 120 }}
  paddingBottom={{ zero: 220, tiny: 400, medium: 230 }}

  etc...
```

### CSS Output
_(from copy/pasting CSS code directly from the injected `style` tag in the `<head>`:)_
```css
.jYZJIX {
  ...a lot of other styles
  padding-top: 20px;
  padding-bottom: 220px;
}

@media screen and (min-width:48em) {
  .jYZJIX {
    padding-top: 120px;
    padding-bottom: 230px;
  }
}

@media screen and (min-width:20em) {
  .jYZJIX {
    padding-bottom: 400px;
  }
}
```


### My testing environment
Mac - Chrome - version `75.0.3770.142`
`styled-system` - version `5.0.5`
`styled-components` - version `4.3.2`

### Theory

The `merge` function in the `@styled-system/core/src/index.js` file does not re-order media queries based on smallest to largest, but rather maintains the order in which they are applied via props. I was able to log out `Object.keys(styles)` inside the `createParser` function, which shows that the media queries are ordered based on the order of the original component props. 

**Example:**
```js
[
  "paddingTop",
  "@media screen and (min-width: 48em)",
  "paddingRight",
  "paddingBottom",
  "@media screen and (min-width: 20em)"
]
```

So, in my example, since `paddingTop` is listed first, both it's raw `paddingTop` value and the corresponding `@media screen and (min-width: 48em)` media query value are added to the `styles` Object. Then, later on, `paddingBottom` is added with its raw value and corresponding media query, which happens to be smaller. This smaller media query value being added **after** the larger value carries on through into `styled-components` and renders the css in an unexpected order, thus causing the issue.

I am starting to work through an ordering function that ties into the `merge` function, but am wary since I have yet to account for all use-cases. My initial plan was to simply sort the resultant `styles` object by key name, forcing smaller media query values to alphabetize above larger. I have yet to test the various scenarios, but wanted to mention the idea to see if it helped.
