### ISSUE TITLE
Using variant breaks the first CSS property

### ISSUE THREAD

**Issue by drakang4** [styled-system/styled-system#594]
In this example: https://codesandbox.io/s/proud-water-3j1zt

I made a `Text` component with `variant` function using this theme.

```jsx
const theme = {
  textStyles: {
    big: {
      fontSize: "56px",
      fontWeight: 700
    },
    small: {
      fontSize: "24px",
      fontWeight: 400
    }
  }
};
```

So 'big' variant is expected to generate styles like this

```css
.asdfgh {
  font-size: 56px;
  font-weight: 700;
}
```

But it actually generates which has incorrect syntax
```css
.asdfgh {
  text-style: font-size:56px;
  font-weight: 700;
}
```
